package main

const tmp = `// Code generated by SetGen[https://github.com/SeananXu/go-set#setgen]. DO NOT EDIT.
/*
MIT License

Copyright (c) 2021 Seanan Xu

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Package set implements a set backed by a hash map.
//
// Reference: https://en.wikipedia.org/wiki/Set_%28abstract_data_type%29
package {{.pkg}}

import (
	"fmt"
	"sort"
	"strings"
{{if .ipt}}{{if .light}}
	"{{.ipt}}"
){{else}}
	"{{.ipt}}"

	"github.com/SeananXu/go-set"
){{end}}{{else}}{{if .light}}){{else}}
	"github.com/SeananXu/go-set"
){{end}}{{end}}{{if .light}}

// ErrBreakEach breaks that the EachE traverses the elements in the set.
var ErrBreakEach = errors.New("break each func"){{end}}

// {{.st}} is a {{.tp}} collection that contains no duplicate elements, without any particular order.
// It supports typical set operations: Core set-theoretical operations, Static sets, Dynamic
// sets, Additional operations.
type {{.st}} map[{{.tp}}]struct{}

// New{{.st}} initializes a new {{.st}}.
func New{{.st}}(elements ...{{.tp}}) {{.st}} {
	s := {{.st}}{}
	s.Add(elements...)
	return s
}

// New{{.st}}WithSize initializes a new {{.st}} with the specified size.
func New{{.st}}WithSize(size int) {{.st}} {
	return make(map[{{.tp}}]struct{}, size)
}

// Add adds the elements to {{.st}}, if it is not present already.
func (s {{.st}}) Add(elements ...{{.tp}}) {
	for _, element := range elements {
		s[element] = struct{}{}
	}
}

// Remove removes the element from {{.st}}, if it is present.
func (s {{.st}}) Remove(elements ...{{.tp}}) {
	for _, element := range elements {
		delete(s, element)
	}
}

// Pop returns an arbitrary element of {{.st}}, deleting it from {{.st}}.
// The second value is a bool that is true if the elements existed in
// the {{.st}}, and false if not.
func (s {{.st}}) Pop() ({{.tp}}, bool) {
	for k := range s {
		delete(s, k)
		return k, true
	}
	return {{.obj}}, false
}

// Size returns the number of elements in {{.st}}.
func (s {{.st}}) Size() int {
	return len(s)
}

// IsEmpty returns whether the {{.st}} is Empty.
func (s {{.st}}) IsEmpty() bool {
	return len(s) == 0
}

// Clear removes all items from the {{.st}}.
func (s *{{.st}}) Clear() {
	*s = make(map[{{.tp}}]struct{})
}

// Has judges the specified element whether exists in the {{.st}}.
// it returns true if existed, and false if not.
func (s {{.st}}) Has(element {{.tp}}) bool {
	_, ok := s[element]
	return ok
}

// HasAll looks for the specified elements to judge
// whether all exist in the {{.st}}.
// it returns true if existed, and false if not.
func (s {{.st}}) HasAll(elements ...{{.tp}}) bool {
	for _, element := range elements {
		if _, ok := s[element]; !ok {
			return false
		}
	}
	return true
}

// HasAny looks for the specified elements to judge
// whether at least one of the element exists in the {{.st}}.
// it returns true if existed, and false if not.
func (s {{.st}}) HasAny(elements ...{{.tp}}) bool {
	for _, element := range elements {
		if _, ok := s[element]; ok {
			return true
		}
	}
	return false
}

// List returns the all elements as a slice.
func (s {{.st}}) List() []{{.tp}} {
	var dest []{{.tp}}
	for k := range s {
		dest = append(dest, k)
	}
	return dest
}

// SortedList returns the all elements as a slice sorted by less func.
func (s {{.st}}) SortedList(less func(i, j {{.tp}}) bool) []{{.tp}} {
	dest := s.List()
	sort.Slice(dest, func(i, j int) bool {
		return less(dest[i], dest[j])
	})
	return dest
}

// EachE traverses the elements in the {{.st}}, calling do func for each
// {{.st}} member. the cycle will be stopped when the do func returns error.
// if err is ErrBreakEach, break the cycle and return nil,
// else, break the cycle and return error.
func (s {{.st}}) EachE(do func(i {{.tp}}) error) error {
	for k := range s {
		if err := do(k); err != nil {
			if err == {{ if .light }}ErrBreakEach{{else}}set.ErrBreakEach{{end}} {
				return nil
			}
			return err
		}
	}
	return nil
}

// Each traverses the elements in the {{.st}}, calling do func for each
// {{.st}} member.
func (s {{.st}}) Each(do func(i {{.tp}})) {
	for k := range s {
		do(k)
	}
}

// Union returns the union of {{.st}} s and t.
// For example:
// s = {a, b, c}
// s = {a, c, d, e, f}
// s.Union(s) = {a, b, c, d, e, f}
// s.Union(s) = {a, b, c, d, e, f}
// s.Union(s) = s.Union(s)
func (s {{.st}}) Union(t {{.st}}) {{.st}} {
	// in order to reduce the number of growing map, copy the largest map here
	var max, min {{.st}}
	if s.Size() > t.Size() {
		max = s
		min = t
	} else {
		max = t
		min = s
	}
	if max.Size() == 0 {
		return New{{.st}}()
	}
	u := max.Copy()
	for k := range min {
		u[k] = struct{}{}
	}
	return u
}

// Difference returns the difference of {{.st}} s and t.
// For example:
// s = {a, b, c}
// s = {a, c, d, e, f}
// s.Difference(s) = {b}
// s.Difference(s) = {d, e, f}
func (s {{.st}}) Difference(t {{.st}}) {{.st}} {
	u := New{{.st}}()
	for k := range s {
		if !t.Has(k) {
			u.Add(k)
		}
	}
	return u
}

// Intersection returns the intersection of {{.st}} s and t.
// For example:
// s = {a, b, c}
// s = {a, c, d, e, f}
// s.Intersection(s) = {a, c}
// s.Intersection(s) = {a, c}
// s.Intersection(s) = s.Intersection(s)
func (s {{.st}}) Intersection(t {{.st}}) {{.st}} {
	var max, min {{.st}}
	if s.Size() > t.Size() {
		max = s
		min = t
	} else {
		max = t
		min = s
	}
	u := New{{.st}}()
	if min.Size() > 0 {
		for k := range min {
			if max.Has(k) {
				u[k] = struct{}{}
			}
		}
	}
	return u
}

// SymmetricDifference returns a new {{.st}} with the elements that are either in this {{.st}}
// or in the given {{.st}}, but not in both.
// For example:
// s = {a, c}
// s = {a, b, d}
// s.SymmetricDifference(s) = {c, b, d}
// s.SymmetricDifference(s) = {c, b, d}
// s.SymmetricDifference(s) = s.SymmetricDifference(s)
func (s {{.st}}) SymmetricDifference(t {{.st}}) {{.st}} {
	return s.Difference(t).Union(t.Difference(s))
}

// IsSubset predicates that tests whether the {{.st}} s is a subset of {{.st}} t.
// For example:
// s is subset of s
// s = {a, b, c}
// s = {a, b, c, d}
// s is not subset of s
// s = {a, f}
// s = {a, b, c, d}
func (s {{.st}}) IsSubset(t {{.st}}) bool {
	for k := range s {
		if !t.Has(k) {
			return false
		}
	}
	return true
}

// IsSuperset predicates that tests whether the {{.st}} s is a super of {{.st}} t.
// For example:
// s is super of s
// s = {a, b, c, d}
// s = {a, b, c}
// s is not super of s
// s = {a, f}
// s = {a, b, c, d}
func (s {{.st}}) IsSuperset(t {{.st}}) bool {
	return t.IsSubset(s)
}

// Equal predicates that tests whether the {{.st}} s equals of {{.st}} t.
// For example:
// s equals of s
// s = {a, b, c}
// s = {a, b, c}
// s does not equal of s
// s = {a, f}
// s = {a, b, c, d}
func (s {{.st}}) Equal(t {{.st}}) bool {
	return len(s) == len(t) && s.IsSubset(t)
}

// Copy returns new {{.st}} that clones from {{.st}}.
func (s {{.st}}) Copy() {{.st}} {
	t := New{{.st}}WithSize(len(s))
	for k := range s {
		t[k] = struct{}{}
	}
	return t
}

// String returns a string representation of {{.st}}
func (s {{.st}}) String() string {
	v := make([]string, 0, s.Size())
	for element := range s {
		v = append(v, fmt.Sprintf("%v", element))
	}
	return fmt.Sprintf("[%s]", strings.Join(v, ", "))
}
`
